-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- INTEREST_CATEGORY Table Create SQL
CREATE TABLE INTEREST_CATEGORY
(
    `INTEREST_NUM`  INT            NOT NULL        COMMENT '분류 번호', 
    `INTEREST_NAME` VARCHAR(45)    NOT NULL        COMMENT '이름', 
    PRIMARY KEY (INTEREST_NUM)
);

ALTER TABLE INTEREST_CATEGORY COMMENT '흥미분야';

-- CLUB Table Create SQL
CREATE TABLE CLUB
(
    `CLUB_NUM`      INT             NOT NULL    AUTO_INCREMENT  COMMENT '동아리 번호', 
    `CLUB_NAME`     VARCHAR(45)     NOT NULL    COMMENT '동아리명', 
    `INTRO`         VARCHAR         NOT NULL    COMMENT '동아리 소개', 
    `CONTENT`       VARCHAR         NOT NULL    COMMENT '활동내용', 
    `EMAIL`         VARCHAR(45)     NOT NULL    COMMENT '팀장 이메일',
    `TIME`          TIMESTAMP       NOT NULL    COMMENT '생성일자', 
    `NICKNAME`      VARCHAR(45)                 COMMENT '팀장 별명',  
    `MEMBER_COUNT`  INT             NOT NULL    DEFAULT 0       COMMENT '멤버 수',
    PRIMARY KEY (CLUB_NUM)
);

ALTER TABLE CLUB AUTO_INCREMENT=1;

ALTER TABLE CLUB COMMENT '동아리';

ALTER TABLE CLUB
ADD CONSTRAINT FK_CLUB_INTEREST_N_INTEREST_CATEGORY_INTEREST_N FOREIGN KEY (INTEREST_NUM)
REFERENCES INTEREST_CATEGORY (INTEREST_NUM);

ALTER TABLE CLUB
ADD CONSTRAINT FK_CLUB_EMAIL_MEMBER_EMAIL FOREIGN KEY (EMAIL)
REFERENCES MEMBER (EMAIL)

ALTER TABLE CLUB
ADD CONSTRAINT FK_CLUB_AREA_NUM_AREA_AREA_NUM FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM)

-- AREA Table Create SQL
CREATE TABLE AREA
(
    `AREA_NUM`   INT            NOT NULL    COMMENT '지역 번호', 
    `AREA_NAME`  VARCHAR(45)    NOT NULL    COMMENT '지역명', 
    PRIMARY KEY (AREA_NUM)
);

ALTER TABLE AREA COMMENT '지역';

-- MEMBER Table Create SQL
CREATE TABLE MEMBER
(
    `EMAIL`      VARCHAR(45)    NOT NULL    COMMENT '아이디', 
    `NAME`       VARCHAR(45)                COMMENT '이름',  
    `GENDER`     VARCHAR(45)                COMMENT '성별',  
    `BIRTH_YEAR` INT                        COMMENT '출생연도',  
    `BIRTH_MONTH`INT                        COMMENT '생일-월',  
    `BIRTH_DAY`  INT                        COMMENT '생일-일',  
    `NICKNAME`   INT                        COMMENT '별명',
    `AREA_NUM`   INT                        COMMENT '지역',
    `GRADE`      INT                        COMMENT '등급',
    PRIMARY KEY(EMAIL)
);

ALTER TABLE MEMBER COMMENT '멤버';

ALTER TABLE MEMBER
ADD CONSTRAINT FK_MEMBER_AREA_NUM_AREA_AREA_N FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM);


-- CLUB_MEMBER Table Create SQL
CREATE TABLE CLUB_MEMBER
( 
    `EMAIL`     VARCHAR(45)    NOT NULL     COMMENT '멤버 이메일'
    `CLUB_NUM`       INT       NOT NULL     COMMENT '클럽 번호', 
    PRIMARY KEY (EMAIL, CLUB_NUM)
);

ALTER TABLE CLUB_MEMBER COMMENT '동아리멤버';

ALTER TABLE CLUB_MEMBER
ADD CONSTRAINT FK_CLUB_MEMBER_CLUB_NUM_CLUB_C FOREIGN KEY (CLUB_NUM)
REFERENCES CLUB (CLUB_NUM)

ALTER TABLE CLUB_MEMBER
ADD CONSTRAINT FK_CLUB_MEMBER_EMAIL_MEMBER_EM FOREIGN KEY (EMAIL)
REFERENCES MEMBER (EMAIL)

-- MEMBER_INTEREST Table Create SQL
CREATE TABLE MEMBER_INTEREST
(
    `EMAIL`         VARCHAR (45)    NOT NULL   COMMENT '이메일', 
    `INTEREST_NUM`  INT             NOT NULL   COMMENT '흥미 번호'
    PRIMARY KEY (EMAIL, INTEREST_NUM)
);

ALTER TABLE MEMBER_INTEREST COMMENT '멤버흥미';

ALTER TABLE MEMBER_INTEREST
ADD CONSTRAINT FK_MEMBER_INTEREST_EMAIL_MEMBE FOREIGN KEY (EMAIL)
REFERENCES MEMBER (EMAIL);

ALTER TABLE MEMBER_INTEREST
ADD CONSTRAINT FK_MEMBER_INTEREST_INTEREST_NU FOREIGN KEY (INTEREST_NUM)
REFERENCES INTEREST_CATEGORY (INTEREST_NUM);

-- CATEGORY Table Create SQL
CREATE TABLE CATEGORY
(
    `CATEGORY_NUM`   INT            NOT NULL    COMMENT '카테고리 번호', 
    `CATEGORY_NAME`  VARCHAR(45)    NOT NULL    COMMENT '카테고리 이름', 
    PRIMARY KEY (CATEGORY_NUM)
);

ALTER TABLE CATEGORY COMMENT '게시글 카테고리';

-- BOARD Table Create SQL
CREATE TABLE BOARD
(
    `POSTNUM`       INT            NOT NULL     AUTO_INCREMENT  COMMENT '글번호', 
    `CATEGORY_NUM`  INT            NOT NULL     COMMENT '카테고리', 
    `TIME`          TIMESTAMP      NOT NULL     COMMENT '작성일자', 
    `TITLE`         VARCHAR(45)    NOT NULL     COMMENT '제목', 
    `CONTENT`       VARCHAR        NOT NULL     COMMENT '내용', 
    `NICKNAME`      VARCHAR(45)                 COMMENT '작성자 별명',
    `EMAIL`         VARCHAR(45)    NOT NULL     COMMENT '작성자 이메일',
    `RECOMMEND`     INT            NOT NULL     DEFAULT 0       COMMENT '추천' 
    PRIMARY KEY (POSTNUM)
);

ALTER TABLE BOARD COMMENT '게시판';

ALTER TABLE BOARD AUTO_INCREMENT=1;

ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_EMAIL_MEMBER_EMAIL FOREIGN KEY (EMAIL)
REFERENCES MEMBER (EMAIL)

ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_CATEGORY_NUM_CATEGORY FOREIGN KEY (CATEGORY_NUM)
REFERENCES CATEGORY (CATEGORY_NUM)


-- FAQ Table Create SQL
CREATE TABLE FAQ
(
    `FAQ_NUM`       INT            NOT NULL     AUTO_INCREMENT COMMENT '글번호', 
    `TITLE`         VARCHAR(45)    NOT NULL     COMMENT '제목', 
    `CONTENT`       VARCHAR        NOT NULL     COMMENT '내용', 
    PRIMARY KEY (FAQ_NUM)
);

ALTER TABLE FAQ COMMENT 'FAQ';

ALTER TABLE FAQ AUTO_INCREMENT=1;

-- QNA Table Create SQL
CREATE TABLE QNA
(
    `NICKNAME`  VARCHAR(45)    NOT NULL    COMMENT '작성자 별명',
    `EMAIL`     VARCHAR(45)    NOT NULL    COMMENT '작성자 이메일',
    `QNA_NUM`   INT            NOT NULL    AUTO_INCREMENT COMMENT '질문 번호', 
    `TIME`      TIMESTAMP      NOT NULL    COMMENT '작성일자', 
    `TITLE`     VARCHAR(45)    NOT NULL    COMMENT '제목', 
    `CONTENT`   VARCHAR        NOT NULL    COMMENT '내용', 
    PRIMARY KEY (QNA_NUM)
);

ALTER TABLE QNA COMMENT 'QNA';

ALTER TABLE QNA AUTO_INCREMENT=1;  

ALTER TABLE QNA
ADD CONSTRAINT FK_QNA_EMAIL_MEMBER_EMAIL FOREIGN KEY (EMAIL)
REFERENCES MEMBER (EMAIL);

-- COMMENT Table Create SQL
CREATE TABLE COMMENT
(
    `NICKNAME`  VARCHAR(45)   NOT NULL    COMMENT '작성자 별명',
    `EMAIL`     VARCHAR(45)   NOT NULL    COMMENT '작성자 이메일',
    `POST_NUM`  INT           NOT NULL    COMMENT '글번호', 
    `CONTENT`   VARCHAR       NOT NULL    COMMENT '내용', 
    `TIME`      TIMESTAMP     NOT NULL    COMMENT '작성시간', 
    `CO_NUM`    INT           NOT NULL    AUTO_INCREMENT COMMENT '댓글번호', 
    PRIMARY KEY (CO_NUM)
);

ALTER TABLE COMMENT COMMENT '댓글';

ALTER TABLE COMMENT AUTO_INCREMENT=1;

ALTER TABLE COMMENT
ADD CONSTRAINT FK_COMMENT_POST_NUM_BOARD_POST FOREIGN KEY (POST_NUM)
REFERENCES BOARD (POSTNUM);

ALTER TABLE COMMENT
ADD CONSTRAINT FK_COMMENT_EMAIL_MEMBER_EMAIL FOREIGN KEY (EMAIL)
REFERENCES MEMBER (EMAIL)

-- RECOMMEND Table Create SQL
CREATE TABLE RECOMMEND
(
    `EMAIL`     VARCHAR(45)    NOT NULL    COMMENT '작성자 이메일',
    `POST_NUM`  VARCHAR(45)    NOT NULL    COMMENT '글번호'
    PRIMARY KEY (EMAIL, POST_NUM)
);

ALTER TABLE RECOMMEND COMMENT '추천';

-- CLUB_INTEREST Table Create SQL
CREATE TABLE CLUB_INTEREST
(
    `CLUB_NUM`      INT    NOT NULL    COMMENT '클럽 번호',
    `INTEREST_NUM`  INT    NOT NULL    COMMENT '카테고리 번호'
    PRIMARY KEY (CLUB_NUM, INTEREST_NUM)
);

ALTER TABLE CLUB_INTEREST COMMENT '동아리 분류';

ALTER TABLE CLUB_INTEREST
ADD CONSTRAINT FK_CI_CN_CLUB_CN FOREIGN KEY (CLUB_NUM)
REFERENCES CLUB (CLUB_NUM);

ALTER TABLE CLUB_INTEREST
ADD CONSTRAINT FK_CI_IN_IC_IN FOREIGN KEY (INTEREST_NUM)
REFERENCES INTEREST_CATEGORY (INTEREST_NUM)


-- CLUB_AREA Table Create SQL
CREATE TABLE CLUB_AREA
(
    `CLUB_NUM`      INT    NOT NULL    COMMENT '클럽 번호',
    `AREA_NUM`      INT    NOT NULL    COMMENT '지역 번호'
    PRIMARY KEY (CLUB_NUM, AREA_NUM)
);

ALTER TABLE CLUB_INTEREST COMMENT '동아리 지역';

ALTER TABLE CLUB_AREA
ADD CONSTRAINT FK_CA_CN_CLUB_CN FOREIGN KEY (CLUB_NUM)
REFERENCES CLUB (CLUB_NUM);

ALTER TABLE CLUB_AREA
ADD CONSTRAINT FK_CA_AN_AREA_AN FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM)